name: musicalization
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.3
  path_provider: ^2.1.0


  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - images/mp3_background.png
    - images/Mp3_ICON.png
    - images/mp3_menu_auto_sound_control.png
    - images/mp3_menu_lyrics_setting.png
    - images/mp3_menu_name_change_button.png
    - images/mp3_menu_picture_setting.png
    - images/mp3_ui_back_music.png
    - images/mp3_ui_delete.png
    - images/mp3_ui_down_arrow.png
    - images/mp3_ui_down_arrow_ex.png
    - images/mp3_ui_google_drive_button.png
    - images/mp3_ui_home.png
    - images/mp3_ui_list.png
    - images/mp3_ui_listgroup.png
    - images/mp3_ui_listgroup_make.png
    - images/mp3_ui_list_add.png
    - images/mp3_ui_list_make.png
    - images/mp3_ui_list_mode.png
    - images/mp3_ui_loop_button_off.png
    - images/mp3_ui_loop_button_on.png
    - images/mp3_ui_loop_list_button.png
    - images/mp3_ui_lyrics.png
    - images/mp3_ui_main_mode.png
    - images/mp3_ui_mp3player_letters.png
    - images/mp3_ui_music_mode.png
    - images/mp3_ui_music_register_button.png
    - images/mp3_ui_music_shuffle_button.png
    - images/mp3_ui_music_stop_button.png
    - images/mp3_ui_next_music.png
    - images/mp3_ui_play_button.png
    - images/mp3_ui_register_mode.png
    - images/mp3_ui_return.png
    - images/mp3_ui_setting_button.png
    - images/mp3_ui_setyoursize_letters.png
    - images/mp3_ui_sound_control_mute_off.png
    - images/mp3_ui_sound_control_mute_on.png
    - images/mp3_ui_sound_control_unmute_off.png
    - images/mp3_ui_sound_control_unmute_on.png
    - images/mp3_ui_update.png


  uses-material-design: true


fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/NotoSansJP-Black.ttf
        weight: 900
      - asset: assets/fonts/NotoSansJP-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSansJP-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSansJP-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSansJP-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSansJP-Thin.ttf
        weight: 100
